server:
  port: 8080

spring:
  application:
    name: cotizacion-envio

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.logistica.cotizacionenvio: DEBUG
